blog/article/urls.py
from django.conf.urls import url
from article import views


urlpatterns = [
    url(r'^$', views.article, name='article'),
    url(r'^articleCreate/$', views.articleCreate, name='articleCreate'),
    url(r'^articleRead/(?P<articleId>[0-9]+)/$', views.articleRead, name='articleRead'),
    url(r'^articleUpdate/(?P<articleId>[0-9]+)/$', views.articleUpdate, name='articleUpdate'),
    url(r'^articleDelete/(?P<articleId>[0-9]+)/$', views.articleDelete, name='articleDelete'),
    url(r'^articleSearch/$', views.articleSearch, name='articleSearch'),



]

blog/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^article/', include('article.urls', namespace='article')),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^.*', include('main.urls')),
]

blog/main/urls.py
from django.conf.urls import url
from main import views


urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^about/$', views.about, name='about'),
    
]

blog/article/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=128, unique=True)
    content = models.TextField()
    pubDateTime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-pubDateTime']


class Comment(models.Model):
    article = models.ForeignKey(Article)
    content = models.CharField(max_length=128)
    pubDateTime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.article.title + '-' + str(self.id)
    
    class Meta:
        ordering = ['pubDateTime']

blog/main/models.py
from django.db import models

# Create your models here.

blog/article/forms.py
from django import forms
from article.models import Article


class ArticleForm(forms.ModelForm):
    title = forms.CharField(label='標題', max_length=128)
    content = forms.CharField(label='內容', widget=forms.Textarea)

    class Meta:
        model = Article
        fields = ['title', 'content']

blog/article/views.py
from django.shortcuts import render, redirect, get_object_or_404

from article.models import Article, Comment
from article.forms import ArticleForm
from django.contrib import messages
from django.db.models.query_utils import Q


# Create your views here.

def article(request):
    '''
    Render the article page
    '''
    articles = Article.objects.all()
    itemList = []
    for article in articles:
        items = [article]
        items.extend(list(Comment.objects.filter(article=article)))
        itemList.append(items)
    context = {'itemList':itemList}
    return render(request, 'article/article.html', context)

def articleCreate(request):
    '''
    Create a new article instance
        1. If method is GET, render an empty form
        2. If method is POST, perform form validation and display error messages if the form is invalid
        3. Save the form to the model and redirect the user to the article page
    '''

    template = 'article/articleCreateUpdate.html'
    if request.method == 'GET':
        print(ArticleForm())
        return render(request, template, {'articleForm':ArticleForm()})
    
    # POST
    articleForm = ArticleForm(request.POST)
    if not articleForm.is_valid():
        return render(request, template, {'articleForm':articleForm})
    articleForm.save()
    messages.success(request, '文章已新增')
    return redirect('article:article')


def articleRead(request, articleId):
    '''
    Read an article
        1. Get the "article" instance using "articleId"; redirect to the 404 page if not found
        2. Render the articleRead template with the article instance and its
           associated comments
    '''
    article = get_object_or_404(Article, id=articleId)
    context = {
        'article': article,
        'comments': Comment.objects.filter(article=article)
    }
    return render(request, 'article/articleRead.html', context)


def articleUpdate(request, articleId):
    '''
    Update the article instance:
        1. Get the article to update; redirect to 404 if not found
        2. Render a bound form if the method is GET
        3. If the form is valid, save it to the model, otherwise render a
           bound form with error messages
    '''
    article = get_object_or_404(Article, id=articleId)
    template = 'article/articleCreateUpdate.html'
    if request.method == 'GET':
        articleForm = ArticleForm(instance=article)
        return render(request, template, {'articleForm':articleForm})
    # POST
    articleForm = ArticleForm(request.POST, instance=article)
    if not articleForm.is_valid():
        return render(request, template, {'articleForm':articleForm})
    articleForm.save()
    messages.success(request, '文章已修改') 
    return redirect('article:articleRead', articleId=articleId)

def articleDelete(request, articleId):
    '''
    Delete the article instance:
        1. Render the article page if the method is GET
        2. Get the article to delete; redirect to 404 if not found
    '''
    if request.method == 'GET':
        return article(request)
    # POST
    articleToDelete = get_object_or_404(Article, id=articleId)
    articleToDelete.delete()
    messages.success(request, '文章已刪除')  
    return redirect('article:article')


def articleSearch(request):
    '''
    Search for articles:
        1. Get the "searchTerm" from the HTML page
        2. Use "searchTerm" for filtering
    '''
    searchTerm = request.GET.get('searchTerm')
    articles = Article.objects.filter(Q(title__icontains=searchTerm) |
                                      Q(content__icontains=searchTerm))
    context = {'articles':articles, 'searchTerm':searchTerm} 
    return render(request, 'article/articleSearch.html', context)

blog/main/views.py
import datetime
import random

from django.shortcuts import render



def main(request):
    '''
    Render the main page
    '''
    now=datetime.datetime.now()
    context = {'like':'Django 很棒', 'now':now}
    return render(request, 'main/main.html', context)


def about(request):
    '''
    Render the about page
    '''
    return render(request, 'main/about.html')

blog/article/templates/article/article.html
% extends 'main/base.html' %}
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" href="{% static 'article/css/article.css' %}">
{% endblock %}
{% block heading %}歡迎蒞臨{% endblock %}
{% block content %}
{% include 'article/searchForm.html' %}
<p class="inlineBlock"><a class="btn" href="{% url 'article:articleCreate' %}">新增文章</a></p>

  ...

  {% endfor %}
  <hr>
{% endfor %}
{% endblock %}
{% block script %}
  <script src={% static 'main/js/deleteConfirm.js' %}></script>
{% endblock %}
    {% for items in itemList %}
      {% for item in items %}
        {% if forloop.first %}
          <h3 class="inlineBlock"><a href="{% url 'article:articleRead' item.id %}">{{ item.title }}</a></h3>
        <form class="inlineBlock" method="post" action="{% url 'article:articleDelete' item.id %}">
        {% csrf_token %}
        <input class="btn deleteConfirm" type="submit" value="刪除">
        </form>
          <p>發表時間：{{ item.pubDateTime|date:'Y-m-d H:i' }}</p>
          <div class="articleContent">{{ item.content|linebreaks|truncatechars_html:30 }}</div>
        {% else %}
          <div class="commentDiv">
            <span class="comment">{{ item.content }}</span><br>
            <span class="commentTime">{{ item.pubDateTime|date:'m月d日 H:i' }}</span>
          </div>
        {% endif %}
      {% endfor %}
      <hr>
    {% endfor %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src={% static 'main/js/deleteConfirm.js' %}></script>
  </body>
</html> 

blog/article/templates/article/articleCreateUpdate.html
% extends 'main/base.html' %}
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" href="{% static 'article/css/article.css' %}">
{% endblock %}
{% block heading %}
  {% if articleForm.instance.id %}
    修改文章
  {% else %}
    新增文章
  {% endif %}
{% endblock %}
{% block content %}
{% if articleForm.instance.id %}
  <h2>修改文章</h2> 
  <form method="post" action="{% url 'article:articleUpdate' articleForm.instance.id %}"> 
{% else %}
  <h2>新增文章</h2> 
  <form method="post" action="{% url 'article:articleCreate' %}"> 
{% endif %}
      {% csrf_token %}
      {{ articleForm.as_p }}
      <input class="btn" type="submit" value="送出">
      <a class="btn" href="{% url 'article:article' %}">放棄</a>
    </form>
{% endblock %}

blog/article/templates/article/articleRead.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" href="{% static 'article/css/article.css' %}">
{% endblock %}
{% block heading %}閱讀文章{% endblock %}
{% block content %}
    <h3 class="inlineBlock">{{ article.title }}</h3>
    <a class="btn inlineBlock" href="{% url 'article:articleUpdate' article.id %}">修改</a>
    <p>發表時間：{{ article.pubDateTime|date:'Y-m-d H:i' }}</p>
    <div class="articleContent">{{ article.content|linebreaks }}</div>
    {% for comment in comments %}
      <div class="commentDiv">
        <span class="comment">{{ comment.content }}</span><br>
        <span class="commentTime">{{ comment.pubDateTime|date:'Y-m-d H:i'}}</span>
      </div>
    {% endfor %}
  {% endblock %}

blog/article/templates/article/articleSearch.html
% extends 'main/base.html' %}
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" href="{% static 'article/css/article.css' %}">
{% endblock %}
{% block heading %}搜尋{% endblock %}
{% block content %}
{% include 'article/searchForm.html' %}
<br><br><hr>
{% if not articles %}
  <p>查無資料</p>
{% else %}
  <table class="table table-striped table-hover">
    <tr><th>標題</th><th>發表時間</th></tr>
    {% for article in articles %}
    <tr>
      <td><a href="{% url 'article:articleRead' article.id %}">{{ article.title }}</a></td>
      <td>{{ article.pubDateTime|date:'Y-m-d H:i' }}</td>
    </tr>
    {% endfor %}
  </table>
{% endif %}
{% endblock %}

blog/article/templates/article/searchForm.html
<form class="inlineBlock" action="{% url 'article:articleSearch' %}">
  <input type="text" name="searchTerm" {% if searchTerm %}value="{{ searchTerm }}"{% endif %}>
  <input class="btn" type="submit" value="查詢">
</form>

blog/main/templates/main/about.html
{% extends 'main/base.html' %}
{% block heading %}關於{% endblock %}
{% block content %}
<p>歡迎來到我的部落格，您可盡情瀏覽並留言。</p>
{% endblock %}

blog/main/templates/main/base.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>部落格</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    {% block css %}{% endblock %}
  </head>
  <body>
    {% include 'main/menu.html' %}
    <h2>部落格 -- {% block heading %}{% endblock %}</h2>
    {% include 'main/messages.html' %}
    {% block content %}{% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% block script %}{% endblock %}
  </body>
</html>

blog/main/templates/main/main.html
{% extends 'main/base.html' %}
{% block heading %}首頁{% endblock %}
{% block content %}
<p>{{ like }}</p>
{% endblock %}

blog/main/templates/main/menu.html
<ul id="menu">
  <li><a href="{% url 'main:main' %}">首頁</a></li>
  <li><a href="{% url 'main:about' %}">關於</a></li>
  <li><a href="{% url 'article:article' %}">部落格</a></li>
</ul>

blog/main/templates/main/messages.html
{% for message in messages %}
  <p class="{{ message.tags }}">{{ message }}</p>
{% endfor %}